universe = vanilla
notification = Never
IWD = $ENV(HOME)
request_memory = 4.0 GB
request_cpus   = 1
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
transfer_output_files = ""
+FileSystemDomain = "notarealdomain"
executable = /data/user/tvaneede/GlobalFit/reco_processing/NNMFit/notebooks/unblind/passing_fraction/submit_compare_pf.sh
arguments  = --flux-type $(flux_type) --flavor $(flavor)
output = $(LOGDIR)/$(JOBID).out
error  = $(LOGDIR)/$(JOBID).err
log    = $(LOGDIR)/$(JOBID).log
queue 1

