astro:
  class: FluxlessBase
  baseline_weights: fluxless_weight
  parameters: [astro_BPL_3flavor,inel_scale]
  param_specifications:
    inel_scale:
      inelasticity_table: &inelasticity_table /data/ana/Diffuse/NNMFit/resources/inelasticity_tables/NuGen_xsection_fits.json

prompt_hese:
  parameters: [prompt_norm, delta_gamma, CR_grad,inel_scale]

conventional_hese:
  parameters: [conv_norm, delta_gamma, CR_grad, barr_h, barr_w, barr_z, barr_y,inel_scale]

conventional_globalfit:
  parameters: [conv_norm, delta_gamma, CR_grad, barr_h, barr_w, barr_z, barr_y,inel_scale]

prompt_globalfit:
  parameters: [prompt_norm, delta_gamma, CR_grad,inel_scale]

conventional_veto_globalfit:
  parameters: [conv_norm, delta_gamma, CR_grad, barr_h, barr_w, barr_z, barr_y, effective_veto,inel_scale]

prompt_veto_globalfit:
  parameters: [prompt_norm, delta_gamma, CR_grad, effective_veto,inel_scale]
