astro:
  class: FluxlessBase
  baseline_weights: fluxless_weight
  parameters: [astro_BPL_3flavor,inel_scale]
  param_specifications:
    inel_scale:
      inelasticity_table: &inelasticity_table /data/ana/Diffuse/NNMFit/resources/inelasticity_tables/NuGen_xsection_fits.json
