universe = vanilla
executable = /data/user/tvaneede/GlobalFit/reco_processing/muons/hese/filter/filter_hese.sh
notification = Never
IWD = $ENV(HOME)
request_memory = 4.0 GB
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
transfer_output_files = ""
+FileSystemDomain = "notarealdomain"
arguments = --Inputpath $(Inputpath) --Outputfile $(Outputfile)
output = $(LOGDIR)/$(JOBID).out
error = $(LOGDIR)/$(JOBID).err
log = $(LOGDIR)/$(JOBID).log
queue 1