analysis_type: asimov
llh: SAYLLH
detector_configs: [IC86_pass2_SnowStorm_v2_tracks,IC86_pass2_SnowStorm_v2_cscd_muon,IC86_pass2_SnowStorm_v2_cscd_hybrid, IC86_pass2_SnowStorm_v2_cscd_cascade, IC86_pass2_SnowStorm_v2_cscd_cascade_double]

input_params:
  astro_nue_ratio: 1.0
  astro_nutau_ratio: 1.0
  gamma_astro: 2.52
  astro_norm: 1.8
  prompt_norm: 0.0
  conv_norm: 1.0