analysis_type: asimov
llh: SAYLLH
detector_configs: [IC86_pass2_SnowStorm_FTP_HESE_Cascades,IC86_pass2_SnowStorm_FTP_HESE_DoubleCascades,IC86_pass2_SnowStorm_FTP_HESE_Tracks]
input_params:
  gamma: 2.87
  total_astro_norm: 6.3699
  a: 0.4444444444
  b: 0.0
  prompt_norm: 0.0
  conv_norm: 1.0
  # all (other) nuisance parameters at default
